version: "3"

services:
    web:
        image: nginx:latest
        #restart: always
        container_name: nasa_nginx
        ports:
            - 8000:80
            - 8443:443

        volumes:
            - ./data/nasa/log:/var/log/nginx
            - ./data/nasa/data/:/usr/share/nginx/html:ro
#            - ./data/nasa/nginx.conf:/etc/nginx/conf.d/default.conf

        networks:
            nasa-network:
                ipv4_address: 172.22.0.6

networks:
    nasa-network:
        driver: bridge
        ipam:
          config:
            - subnet: 172.22.0.0/16
